name: fl_umeng_apm_example
description: Demonstrates how to use the fl_umeng_apm plugin.
publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_umeng_apm:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
